# Generated by Django 4.2.20 on 2025-07-31 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ra", models.PositiveIntegerField(unique=True, verbose_name="RA")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("fone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("curso", models.CharField(max_length=100, verbose_name="Curso")),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("data_nasc", models.DateField(verbose_name="Data de Nascimento")),
            ],
        ),
        migrations.CreateModel(
            name="Napne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateField(verbose_name="Data de Criação")),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "siape",
                    models.PositiveIntegerField(unique=True, verbose_name="SIAPE"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("fone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("tipo", models.CharField(max_length=50, verbose_name="Tipo")),
                (
                    "napne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginas.napne",
                        verbose_name="NAPNE",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servidor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("fone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Laudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
                ("data", models.DateField(verbose_name="Data do Laudo")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paginas.aluno"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "laudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paginas.laudo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Indicativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("indicativo", models.BooleanField(verbose_name="Indicativo")),
                (
                    "laudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paginas.laudo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aluno",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="paginas.responsavel",
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aluno",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
