# Generated by Django 4.2.20 on 2025-09-21 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.PositiveIntegerField(unique=True, verbose_name='RA')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.curso', verbose_name='Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Napne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(verbose_name='Data de Criação')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.disciplina', verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Pte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(verbose_name='Data de Criação')),
                ('ano_letivo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano Letivo')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Início do PTE')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='Fim do PTE')),
                ('potencialidades_dificuldades_habilidades', models.TextField(blank=True, null=True, verbose_name='Potencialidades, dificuldades e habilidades do estudante')),
                ('recursos_servicos_procedimentos', models.TextField(blank=True, null=True, verbose_name='Recursos, serviços e procedimentos necessários para adaptação')),
                ('expectativas_aprendizagem', models.TextField(blank=True, null=True, verbose_name='Expectativas de aprendizagem pretendidas')),
                ('conteudos_previstos', models.TextField(blank=True, null=True, verbose_name='Conteúdos previstos')),
                ('instrumentos_avaliativos', models.TextField(blank=True, null=True, verbose_name='Instrumentos avaliativos previstos para adaptação')),
                ('anexos', models.TextField(blank=True, null=True, verbose_name='Anexos')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações adicionais')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptes', to='paginas.aluno')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('componente_curricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.disciplina', verbose_name='Componente Curricular')),
                ('professor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.professor', verbose_name='Professor(a) Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.PositiveIntegerField(unique=True, verbose_name='SIAPE')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('napne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.napne', verbose_name='NAPNE')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.servidor', verbose_name='Servidor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioPte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Relatório')),
                ('rel_expectativas_nao_alcancadas', models.TextField(blank=True, null=True, verbose_name='Expectativas de aprendizagem não alcançadas')),
                ('rel_conteudos_nao_alcancados', models.TextField(blank=True, null=True, verbose_name='Conteúdos não alcançados')),
                ('rel_avaliacao_recursos_adaptados', models.TextField(blank=True, null=True, verbose_name='Avaliação da aplicação dos recursos adaptados')),
                ('rel_aspectos_desempenho', models.TextField(blank=True, null=True, verbose_name='Aspectos observados quanto ao desempenho do estudante')),
                ('rel_dificuldades_professor', models.TextField(blank=True, null=True, verbose_name='Dificuldades encontradas pelo professor')),
                ('rel_anexos', models.TextField(blank=True, null=True, verbose_name='Anexos (Relatório)')),
                ('rel_informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações adicionais (Relatório)')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='paginas.pte', verbose_name='PTE')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data do Laudo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.aluno')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.aluno')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.aluno')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('indicativo', models.BooleanField(verbose_name='Indicativo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.aluno')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.responsavel', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
