# Generated by Django 4.2.20 on 2025-09-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='fone',
            field=models.CharField(max_length=16, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=20, verbose_name='Ra'),
        ),
    ]
