# Generated by Django 4.2.20 on 2025-09-22 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_aluno_fone_alter_aluno_ra'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicativo',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.professor'),
        ),
        migrations.AddField(
            model_name='interacoes',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.professor'),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.professor'),
        ),
    ]
